### ISSUE TITLE
tutorial.md contains links that result in a 404

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Blockchain-Archive/vehicle-manufacture#25]
`%PLAYGROUND_URL%` and `%REST_SERVER_URL%` are not getting substituted properly in the following section resulting in invalid URLs:

## Want to go more in-depth?
This sample was built using [IBM Blockchain Platform: Develop](https://console.stage1.bluemix.net/docs/services/blockchain/develop.html#develop-the-network). Check out the model and business logic behind this sample [here](%PLAYGROUND_URL%), or browse the generated REST APIs [here](%REST_SERVER_URL%).

**Comment by altharp** [comment]
@sstone1 I think the changes in https://github.com/IBM-Blockchain/vehicle-manufacture/commit/6de387ed1828ac5ddc47d8e8f6e726a63b1d55ca introduced this issue where the links to information about the business logic and generated REST APIs are not working.  Could you or a colleague take a look at this?

**Comment by cazfletch** [comment]
closing as works for me
