### ISSUE TITLE
Vehicle manufacture samples Toolchain Deploy stage running more than 30 mins

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Blockchain-Archive/vehicle-manufacture#27]
Tried Installing the Vehicle manufacture sample via Toolchain. Initially it failed with Timeout and verified Delivery stage logs. The stage took different space than Blockchain service. Updated the correct Space and clicked on "Run" Deploy Stage. 

After 15 mins I see, the msg composer plyaground installed as below. 

 ---- Installed composer-playground ----- 

However after this,  the pipeline keeps running for more than 40 mins , but not yet completed.
I could see below  apps on dasboard.

"composer-playground-vehicle-manufacture-xxxxx"  - up and running. Could open and see the network.

"composer-rest-server-vehicle-manufacture-xxxx" - Stopped state.

"vehicle-manufacture-20180321123930369" - Stopped State. 

The logs are struck at the last statement as "---- Installed composer-playground ----- " 

Finally, Deploy job  failed with below error after 59mins :(

**The job exceeded the maximum time limit for jobs, and has been terminated.**

**Comment by cazfletch** [comment]
closing as this was a long time ago feel free to reopen if this is still an issue
