### ISSUE TITLE
Unable to launch sample Blockchain of the Vihicle Manufuring

### ISSUE THREAD

**Issue by alanhamid** [IBM-Blockchain-Archive/vehicle-manufacture#32]
Here a  link to a screen shot that might help
https://screenshots.firefox.com/WSsL1mhpXj6LMBu2/ibmblockchain-starter.ng.bluemix.net 
Another error while launching 
https://screenshots.firefox.com/qdiCqFCNECvMJVHH/ibmblockchain-starter.ng.bluemix.net  
Tried about 10 min later.  Now got this error:  
https://screenshots.firefox.com/qPlKdeHxvZ7SFnYd/ibmblockchain-starter.ng.bluemix.net 
Hope this might help to figure out the problem.  
Thanks
Alan

**Comment by dshuffma-ibm** [comment]
@alanhamid your screen shots are not making it through. you can paste the screen shot in your comment directly (instead of linking it).

**Comment by alanhamid** [comment]
I think the link has expired.  Hope this attachment helps

Alan

**Comment by cazfletch** [comment]
closing please reopen with the errors you are seeing if this is still hapening
